### ISSUE TITLE
Host the full dataset (collection) on GIN

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/studyforrest-data#8]
It should have sufficient space and is fully datalad compatible. There are no restrictions re format and specs, hence it can take more than OpenNeuro would.

A worthwhile target would be the assignment of DOIs for each dataset component. For that we would need to provide datacite-compliant records in each subdataset (see #7)

**Comment by adswa** [comment]
I'll record the few relevant steps I performed in https://gin.g-node.org/adswa/processing-workflow-tutorial here:

- Create a new Gin repository and add it as a remote via its SSH url (SSH in order to push data). Use a different name than the one you want to give the special remote. As I wanted to keep it descriptive and call the special remote gin, I called the Git remote gnode: ``git remote add gnode git@gin.g-node.org:/adswa/processing-workflow-tutorial.git```
- Push the data to Gin: ``datalad push --to gnode``
- Reconfigure the SSH url to an HTTPS url. This needs to be done because the remote url needs to be identical to the ``location=<url>`` parameter for the special remote, and the special remote needs an HTTPS url such that users would not need to have a Gin account: `` git remote set-url gnode https://gin.g-node.org/adswa/processing-workflow-tutorial   ``
- Initialize the special remote: `` git annex initremote gin type=git location=https://gin.g-node.org/adswa/processing-workflow-tutorial autoenable=true``

**Comment by mih** [comment]
Here is what I did: https://github.com/datalad-handbook/book/issues/706

**Comment by mih** [comment]
TODO:

- [x] https://gin.g-node.org/studyforrest/cortical-surfaces-freesurfer
- [x] https://gin.g-node.org/studyforrest/retinotopic-maps
- [x] https://gin.g-node.org/studyforrest/aggregate-fmri-timeseries
- [x] https://gin.g-node.org/studyforrest/visual-areas
- [x] https://gin.g-node.org/studyforrest/aligned-mri
- [x] https://gin.g-node.org/studyforrest/imagespace-transformations
- [x] https://gin.g-node.org/studyforrest/curated-annotations

**Comment by mih** [comment]
All non-original datasets are now also on GIN.
